### ISSUE TITLE
Opinion C4

### ISSUE THREAD

**Issue by nicobao** [stephane-klein/personnal-notebook#3]
Hi Stéphane,

I am curious about your opinion on [Pieter Hintjens' C4](https://rfc.zeromq.org/spec/42/)?
The document is [explained in one of Hintjens' books](https://hintjens.gitbooks.io/social-architecture/content/chapter4.html).
Nextcloud thought about using C4, there is an insightful discussion about it on their [related issue](https://help.nextcloud.com/t/should-we-adopt-c4/113).

**Comment by stephane-klein** [comment]
@nicobao thanks you, it's interesting, I'm reading it 👍
